### ISSUE TITLE
Doesn't work with / path and Apache

### ISSUE THREAD

**Issue by eminos** [JosephSilber/page-cache#1] opened 2016-11-30 23:47 UTC
It doesn't seem to work with a root path (/) route and Apache.
The static html file is created with the file name ".html" (and recreated on every request), but I can see that PHP is responding instead of only Apache. The route "/en" is working as expected.

This is my route:
```
Route::get('/{locale?}', function ($locale = 'sv') {
    return view('start')->with('locale', $locale);
})->middleware(['page-cache']);
```

Otherwise, great package :)

**Comment by JosephSilber** [comment] 2016-12-02 05:09
I remember this working when I tested on Apache, but don't have that set up right now.

Will try to spin something up one of these days to test and will report back here.

**Comment by eminos** [comment] 2016-12-03 18:54
One solution could be to let the "no name" routes/files be named "index.html" instead of ".html". And add that RewriteRule to htaccess.

**Comment by JosephSilber** [comment] 2016-12-03 23:05
What if there's an actual index route?

**Comment by JosephSilber** [comment] 2016-12-05 15:09
I can confirm that it indeed does not work.

It seem the reason for this is that this line:

```apacheconf
RewriteCond %{DOCUMENT_ROOT}/page-cache%{REQUEST_URI}.html -f
```

... returns false for files with a leading dot.

One workaround would be to save the root page as `__index__.html`, then put a separate rewrite condition just for the root. The end result would look something like this:

```apacheconf
    RewriteCond %{REQUEST_URI} ^/$
    RewriteCond %{DOCUMENT_ROOT}/page-cache/__index__.html -f
    RewriteRule . page-cache/__index__.html [L]
    RewriteCond %{DOCUMENT_ROOT}/page-cache%{REQUEST_URI}.html -f
    RewriteRule . page-cache%{REQUEST_URI}.html [L]
```

I've been playing with it, but for some reason I can't get that first line to work. It never matches.

I'll have to play with it some more when I get a chance.

**Comment by eminos** [comment] 2016-12-05 15:25
Could it be that the previous default Laravel rewriterule removes the trailing slash?
I think I've gotten this to work in my little tests earlier:

```
RewriteCond %{REQUEST_URI} ^$
```

Not sure though. I will try with your code modification suggestions when I get some time.

**Comment by JosephSilber** [comment] 2016-12-06 14:23
Fixed in https://github.com/JosephSilber/page-cache/commit/b020e21b0965e663507ee828583f3b744e7a3155

Now I have to figure out how to set up the `try_files` for nginx for this...

**Closed by JosephSilber** 2016-12-06 14:23 UTC
